# FORTH CODE WORD: test/ms
# Auto-generated by CODE/ENDCODE
# Original Forth name: ms
#
# === CÓDIGO FORTH ORIGINAL ===
# import time
# milliseconds = pop()
# time.sleep(milliseconds / 1000)
# === FIN CÓDIGO FORTH ===

def execute(forth):
    """
    Ejecuta la palabra CODE 'ms'
    Tiene acceso a helpers: push(), pop(), peek()
    """
    # Helpers
    def push(val):
        forth.stack.append(val)
    
    def pop():
        if not forth.stack:
            raise IndexError("Stack underflow")
        return forth.stack.pop()
    
    def peek():
        if not forth.stack:
            raise IndexError("Stack empty")
        return forth.stack[-1]
    
    # Código del usuario
    import time
    milliseconds = pop()
    time.sleep(milliseconds / 1000)
